# Retain unattached local sessions (tmux's standard behavior).
set-option -g destroy-unattached off

# When a local session is destroyed, move its clients to another session when
# possible instead of detaching them.
set-option -g detach-on-destroy off
