# Keep sessions available when their SSH client disappears.
set-option -g destroy-unattached off

# Move a client to another session, when possible, instead of detaching it when
# its current session is destroyed.
set-option -g detach-on-destroy off
