local function start(command, rules)
    hl.exec_cmd(command, rules)
end

hl.on("hyprland.start", function()
    start("$HOME/.local/bin/hypr-wallpaper-picker restore")
    start("wl-paste --type text --watch $HOME/.config/hypr/scripts/clipboard-store.sh")
    start("wl-paste --type image --watch $HOME/.config/hypr/scripts/clipboard-store.sh")
    start("quickshell")
    start("hypridle")
    start("$HOME/.local/bin/desktop-mode daemon")
    start("~/.config/hypr/scripts/spotify-notify.sh")
    start("$HOME/.config/hypr/scripts/hypr-monitor-watch.py")
    start("helium-browser", { workspace = "2 silent" })
    start("spotify", { workspace = "9 silent" })
    start("virt-manager", { workspace = "6 silent" })
    start("hermes", { workspace = "6 silent" })
    start("obsidian", { workspace = "3 silent" })
    start("t3code", { workspace = "4 silent" })
    start("kitty", { workspace = "1 silent" })
    start("udiskie --automount --notify --no-tray")
end)
