# Enable Powerlevel10k instant prompt. Keep this near the top.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Oh My Zsh path
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins handled by Oh My Zsh
plugins=(
  git
  fzf-tab
)

# Environment
export MANPAGER="nvim +Man!"
export TERM="xterm-256color"

# Aliases
alias ls='eza -al --icons=auto --color=always --group-directories-first'
alias la='eza -a --icons=auto --color=always --group-directories-first'
alias ll='eza -l --icons=auto --color=always --group-directories-first'
alias lt='eza -aT --icons=auto --color=always --group-directories-first'
alias l.='eza -al --icons=auto --color=always --group-directories-first ../'
alias l..='eza -al --icons=auto --color=always --group-directories-first ../../'
alias l...='eza -al --icons=auto --color=always --group-directories-first ../../../'
alias cls='clear'
alias v='nvim'
alias sudo='doas'
alias hack='sudo systemctl stop tailscale && sudo openvpn --config /home/liam/Downloads/vpn/us-east-1-liamdecareaux200-regular.ovpn'
# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# fzf shell integration
[[ -f /usr/share/fzf/key-bindings.zsh ]] && source /usr/share/fzf/key-bindings.zsh
[[ -f /usr/share/fzf/completion.zsh ]] && source /usr/share/fzf/completion.zsh

# fzf-tab config
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' menu no
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':fzf-tab:*' switch-group '<' '>'

# Autosuggestions
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Syntax highlighting must be near the end
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Pokemon
pokemon-colorscripts --no-title -s -r | fastfetch -c $HOME/.config/fastfetch/config-pokemon.jsonc --logo-type file-raw --logo-height 10 --logo-width 5 --logo -

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

# Desktop theme colours for the prompt, fzf and autosuggestions. Generated by
# `theme set <slug>`; sourced *after* .p10k.zsh so it can override the prompt's
# own palette. It only recolours segments -- the prompt's layout and powerline
# shape stay defined in .p10k.zsh.
[[ -f ~/.config/zsh/current-theme.zsh ]] && source ~/.config/zsh/current-theme.zsh

alias gam="/home/liam/bin/gam7/gam"

# Also set for the graphical session by hyprland.lua; guard so a login shell
# under Hyprland does not prepend a duplicate entry.
[[ ":$PATH:" == *":$HOME/.local/bin:"* ]] || export PATH="$HOME/.local/bin:$PATH"

# gpg-agent SSH agent for interactive shells only.
if [[ -o interactive ]]; then
  gnupg_ssh_socket="$(gpgconf --list-dirs agent-ssh-socket 2>/dev/null)" && [[ -n "$gnupg_ssh_socket" ]] || gnupg_ssh_socket=
  if [[ -n "$gnupg_ssh_socket" ]]; then
    export SSH_AUTH_SOCK="$gnupg_ssh_socket"
    export GPG_TTY="$(tty 2>/dev/null)"
    gpg-connect-agent updatestartuptty /bye >/dev/null 2>&1
  fi
  unset gnupg_ssh_socket
fi

# Standalone coding-agent launchers from the `ai` Stow package.
[[ -r ~/.config/ai-agent/shell.zsh ]] && source ~/.config/ai-agent/shell.zsh

# Guarded YubiKey/PAM helpers from the `security` Stow package.
[[ -r ~/.config/yubikey-auth/shell.zsh ]] && source ~/.config/yubikey-auth/shell.zsh

# >>> Codex installer >>>
export PATH="/home/liam/.local/bin:$PATH"
# <<< Codex installer <<<
