pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Wayland

// Centered "scan my clipboard" QR overlay.
//
// Same window shape as WifiQrOverlay, for the same reason: a QR code is meant
// to be held up to a phone, so it gets the middle of the screen rather than a
// corner. One instance per monitor, only the one matching
// ClipboardQrState.overlayScreen visible, overlay layer so it covers the bar,
// exclusive keyboard focus, no space reserved.
//
// The code itself is generated by ClipboardQrState -- this window only renders
// it. Dismissal is deliberate only: Escape, a click on the scrim, or the Back
// button. There is no auto-close timer, because someone holding a phone up to
// the screen should never race one.
PanelWindow {
  id: panel

  required property string ownerScreen

  visible: ClipboardQrState.resultPath !== ""
        && ClipboardQrState.overlayScreen === panel.ownerScreen

  anchors { top: true; bottom: true; left: true; right: true }
  exclusionMode: ExclusionMode.Ignore
  color: "transparent"

  WlrLayershell.layer: WlrLayer.Overlay
  WlrLayershell.keyboardFocus: WlrKeyboardFocus.Exclusive
  WlrLayershell.namespace: "quickshell-clipboard-qr"

  function close() {
    ClipboardQrState.close()
  }

  // -- scrim -----------------------------------------------------------------
  Rectangle {
    anchors.fill: parent
    color: Qt.rgba(Theme.bg.r, Theme.bg.g, Theme.bg.b, Theme.scrimOpacity)

    // Clicking outside the card dismisses the overlay.
    MouseArea {
      anchors.fill: parent
      onClicked: panel.close()
    }
  }

  // -- card ------------------------------------------------------------------
  Rectangle {
    id: card
    anchors.centerIn: parent
    width: Theme.fs(360)
    height: qrContent.implicitHeight + Theme.gapL * 2
    radius: Theme.radiusM
    color: Theme.bg
    border.width: Math.max(1, Theme.borderWidth)
    border.color: Theme.borderAccent

    // Swallows clicks so they do not reach the dismissing scrim.
    MouseArea { anchors.fill: parent }

    FocusScope {
      id: keys
      anchors.fill: parent
      focus: true

      Keys.onEscapePressed: panel.close()

      Column {
        id: qrContent
        anchors.centerIn: parent
        spacing: Theme.gapM

        Text {
          text: "Clipboard"
          color: Theme.text
          font.bold: true
          font.pixelSize: Theme.fs(17)
          anchors.horizontalCenter: parent.horizontalCenter
        }

        Image {
          source: ClipboardQrState.resultPath !== ""
            ? "file://" + ClipboardQrState.resultPath : ""
          // Every generation overwrites the same file, so a cached pixmap
          // would keep showing the previous clipboard forever. Uncached, each
          // re-open reads the SVG back off disk.
          cache: false
          width: Theme.fs(280)
          height: Theme.fs(280)
          fillMode: Image.PreserveAspectFit
          sourceSize.width: width
          sourceSize.height: height
          anchors.horizontalCenter: parent.horizontalCenter
        }

        Rectangle {
          width: Theme.fs(82)
          height: Theme.fs(28)
          radius: Theme.radiusCell
          color: Theme.surface
          anchors.horizontalCenter: parent.horizontalCenter

          Text {
            anchors.centerIn: parent
            text: "Back"
            color: Theme.text
            font.pixelSize: Theme.fs(10)
          }

          MouseArea {
            anchors.fill: parent
            onClicked: panel.close()
          }
        }
      }
    }
  }

  onVisibleChanged: if (visible) keys.forceActiveFocus()
}
